### ISSUE TITLE
Matcha 101: How it Stacks Up

### ISSUE THREAD

**Issue by quinnfenlon** [rmfarrell/teatime-shopify-theme#36]
Is it possible to have these fade a bit more as they transition?  Instead of staying relatively opaque the whole time.

Update subcopy style to the below

![image](https://user-images.githubusercontent.com/40186835/41314510-ce3ae9d2-6e41-11e8-855e-fa562f463493.png)

**Comment by rmfarrell** [comment]
The cross-fade is very difficult to implement here. Otherwise I would have.
