### ISSUE TITLE
Tier 1: Remove Nav Condense Lag

### ISSUE THREAD

**Issue by quinnfenlon** [rmfarrell/teatime-shopify-theme#51]
So, when the nav shrinks up to it's smaller state, it takes like, a second after you begin scrolling - which sometimes fucks up the way it locks up with the product page sub navs.

Can we just have it shrink up immediately on scroll?

**Comment by rmfarrell** [comment]
It's a 200 millisecond lag which I reduced to 100. I don't want to make it zero because you'll start to notice scrolling becomes a little shitty on mobile devices

**Comment by quinnfenlon** [comment]
roger that!
